### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kirovtome** [vtsingaras/xenorchestra_inventory#1]
Hi, 

I'm running the script using python 3.8 and I'm currently stuck on this issue. i would appreciate if you could look into this one.

`[WARNING]:  * Failed to parse /etc/ansible/xenorchestra.py with script plugin: Inventory script (/etc/ansible/xenorchestra.py) had an execution error: Traceback (most recent call last):   File "/etc/ansible/xenorchestra.py", line 130, in <module>     xoa = xo('ws://' + xoa_host, **login_args)   File "/home/ansible/.local/lib/python3.8/site-packages/synthetic/synthetic_constructor_factory.py", line 79, in init     originalConstructor(instance, *args, **kwargs)   File "/home/ansible/.local/lib/python3.8/site-packages/xolib/xo.py", line 45, in __init__     self._learn_methods()   File "/home/ansible/.local/lib/python3.8/site-packages/xolib/xo.py", line 81, in _learn_methods     patch_method_in(self, method_code)   File "/home/ansible/.local/lib/python3.8/site-packages/xolib/utils.py", line 7, in patch_method_in     exec(method_code, None, ld)   File "<string>", line 1     def backupNg_getLogs(self, *, after=None, before=None, limit=None, *): return self.call('backupNg.getLogs', after=after, before=before, limit=limit, *=*)                                                          ^ SyntaxError: invalid syntax  

[WARNING]:  * Failed to parse /etc/ansible/xenorchestra.py with ini plugin: /etc/ansible/xenorchestra.py:3: Expected key=value host variable assignment, got: xolib

[WARNING]: Unable to parse /etc/ansible/xenorchestra.py as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'`

**Comment by kirovtome** [comment]
![Screenshot from 2020-08-18 13-29-12](https://user-images.githubusercontent.com/20068508/90507864-e5f99e80-e156-11ea-8047-63b329c83432.png)

**Comment by luizhpriotto** [comment]
I have the same error =(
